"""Base de dados inicial e estrutura das especificações."""

MODEL_COL = "Modelo / configuração"
PRICE_COL = "Preço atual (R$)"

# Ordem e agrupamento das especificações exibidas na ficha e no comparativo.
GROUPS = {
    "Identificação": ["Marca", "Modelo / configuração", "Código / SKU", "Ano/geração aproximada", "Sistema operacional"],
    "Compra": ["Preço atual (R$)", "Link do anúncio", "Garantia informada"],
    "Processador e gráficos": [
        "CPU", "Família / geração CPU", "Arquitetura CPU", "Núcleos", "P-cores", "E-cores", "LP E-cores", "Threads",
        "Clock base / referência (GHz)", "Turbo máx. (GHz)", "Cache L3 (MB)", "CPU PassMark (multi)", "CPU PassMark (single)",
        "NPU", "GPU", "GPU integrada", "GPU dedicada",
    ],
    "Memória": [
        "RAM instalada (GB)", "Tipo RAM", "Velocidade RAM", "Configuração RAM", "RAM soldada", "Slots RAM físicos",
        "Slots RAM livres", "RAM máxima oficial (GB)", "Dual-channel de fábrica", "Expansão de RAM",
    ],
    "Armazenamento": ["SSD instalado (GB)", "Tipo/interface SSD", "Formato SSD", "Slots M.2 totais", "Slots M.2 livres", "Armazenamento máx./observação"],
    "Tela": ["Tela (pol.)", "Resolução", "Proporção", "Painel", "Acabamento", "Touch", "Taxa de atualização (Hz)", "Brilho (nits)", "Cobertura de cores", "Contraste"],
    "Câmera e entrada": ["Webcam", "Tampa de privacidade", "Teclado ABNT2", "Teclado numérico", "Teclado retroiluminado", "Touchpad"],
    "Conectividade": [
        "Wi‑Fi", "Bluetooth", "Ethernet RJ‑45", "USB‑A", "USB‑C", "Thunderbolt / USB4", "USB‑C com vídeo",
        "USB‑C com carregamento", "HDMI", "Leitor de cartões", "Áudio P2",
    ],
    "Áudio": ["Áudio / alto-falantes", "Microfones"],
    "Bateria e energia": ["Bateria (Wh)", "Células", "Autonomia declarada", "Carregador (W)", "Carregamento USB‑C"],
    "Dimensões e construção": ["Largura (mm)", "Profundidade (mm)", "Espessura (mm)", "Peso (kg)", "Material / construção", "Cor"],
    "Segurança": ["TPM", "Trava de segurança", "Leitor biométrico"],
    "Observações e fontes": ["Resumo", "Destaques objetivos", "Limitações / ressalvas", "Fonte técnica principal", "Fonte complementar"],
}

SPEC_COLUMNS = [col for cols in GROUPS.values() for col in cols]

NUMERIC_FIELDS = {
    "Preço atual (R$)", "Núcleos", "P-cores", "E-cores", "LP E-cores", "Threads", "Clock base / referência (GHz)",
    "Turbo máx. (GHz)", "Cache L3 (MB)", "CPU PassMark (multi)", "CPU PassMark (single)", "RAM instalada (GB)",
    "Slots RAM físicos", "Slots RAM livres", "RAM máxima oficial (GB)", "SSD instalado (GB)", "Slots M.2 totais",
    "Slots M.2 livres", "Tela (pol.)", "Taxa de atualização (Hz)", "Brilho (nits)", "Bateria (Wh)", "Carregador (W)",
    "Largura (mm)", "Profundidade (mm)", "Espessura (mm)", "Peso (kg)",
}

URL_FIELDS = {"Link do anúncio", "Fonte técnica principal", "Fonte complementar"}
LONG_TEXT_FIELDS = {"Resumo", "Destaques objetivos", "Limitações / ressalvas", "Armazenamento máx./observação"}

# Dicas exibidas no formulário de cadastro.
FIELD_HELP = {
    "Preço atual (R$)": "Aceita 3499, 3.499,90 ou 3499.90.",
    "CPU PassMark (multi)": "Nota 'Average CPU Mark' em cpubenchmark.net. Deixe vazio para estimar pelo nome da CPU.",
    "CPU PassMark (single)": "Nota 'Single Thread Rating' em cpubenchmark.net.",
    "GPU": "GPU usada na pontuação. Vazio = dedicada, se houver; senão, a integrada.",
    "Dual-channel de fábrica": "Comece com Sim ou Não. Afeta RAM e GPU integrada.",
    "Brilho (nits)": "Número. Se houver variação (\"220 ou 250\"), o menor valor é usado.",
    "Resumo": "Texto livre exibido na página Resumo.",
}

# Fontes das notas de referência de CPU (PassMark, médias consultadas em out/2026).
NOTEBOOKS = [
    {
        "Marca": "Samsung",
        "Modelo / configuração": "Galaxy Book4 15,6” — i5-1335U / 8GB / 512GB",
        "Código / SKU": "NP750XGJ-KG3BR",
        "Ano/geração aproximada": "2024 / Intel 13ª",
        "Sistema operacional": "Windows 11 Home",
        "CPU": "Intel Core i5-1335U",
        "Família / geração CPU": "13ª geração (Raptor Lake-U)",
        "Arquitetura CPU": "Híbrida",
        "Núcleos": 10,
        "P-cores": 2,
        "E-cores": 8,
        "LP E-cores": 0,
        "Threads": 12,
        "Clock base / referência (GHz)": 1.3,
        "Turbo máx. (GHz)": 4.6,
        "Cache L3 (MB)": 12,
        "NPU": "Não",
        "GPU integrada": "Intel Iris Xe Graphics",
        "GPU dedicada": "Não",
        "RAM instalada (GB)": 8,
        "Tipo RAM": "LPDDR4x",
        "Velocidade RAM": "N/D",
        "Configuração RAM": "8GB onboard",
        "RAM soldada": "Sim",
        "Slots RAM físicos": 0,
        "Slots RAM livres": 0,
        "RAM máxima oficial (GB)": 8,
        "Dual-channel de fábrica": "Sim (LPDDR)",
        "Expansão de RAM": "Não",
        "SSD instalado (GB)": 512,
        "Tipo/interface SSD": "NVMe",
        "Formato SSD": "M.2",
        "Slots M.2 totais": 2,
        "Slots M.2 livres": 1,
        "Armazenamento máx./observação": "SSD expansível; 2 slots M.2 no chassi",
        "Tela (pol.)": 15.6,
        "Resolução": "1920×1080",
        "Proporção": "16:9",
        "Painel": "IPS / LED",
        "Acabamento": "Antirreflexo",
        "Touch": "Não",
        "Taxa de atualização (Hz)": 60,
        "Brilho (nits)": "N/D",
        "Cobertura de cores": "N/D",
        "Contraste": "N/D",
        "Webcam": "HD 720p / 1 MP",
        "Tampa de privacidade": "N/D",
        "Teclado ABNT2": "Sim",
        "Teclado numérico": "Sim",
        "Teclado retroiluminado": "Não informado",
        "Touchpad": "Clickpad",
        "Wi‑Fi": "Wi‑Fi 6 (802.11ax) 2×2",
        "Bluetooth": "5.2",
        "Ethernet RJ‑45": "Sim, Gigabit",
        "USB‑A": "2× USB 3.2",
        "USB‑C": "2× USB‑C",
        "Thunderbolt / USB4": "Não informado",
        "USB‑C com vídeo": "Sim (família)",
        "USB‑C com carregamento": "Sim",
        "HDMI": "1× HDMI (família Book4; versão 2.1 em ficha BR)",
        "Leitor de cartões": "microSD",
        "Áudio P2": "1× combo 3,5 mm",
        "Áudio / alto-falantes": "Estéreo 2×2W, Dolby Atmos",
        "Microfones": "Dual array",
        "Bateria (Wh)": 54,
        "Células": "N/D",
        "Autonomia declarada": "N/D",
        "Carregador (W)": 45,
        "Carregamento USB‑C": "Sim",
        "Largura (mm)": 356.6,
        "Profundidade (mm)": 229.1,
        "Espessura (mm)": 15.4,
        "Peso (kg)": 1.55,
        "Material / construção": "Corpo metálico",
        "Cor": "Grafite",
        "TPM": "Sim",
        "Trava de segurança": "Sim",
        "Leitor biométrico": "Não informado",
        "Garantia informada": "12 meses (mercado BR, confirmar anúncio)",
        "Destaques objetivos": "Leve; bateria 54Wh; RJ‑45; 2 USB‑C; segundo slot SSD",
        "Limitações / ressalvas": "RAM de 8GB soldada e sem expansão; brilho/gamut não publicados na ficha deste SKU",
        "Link do anúncio": "https://www.mercadolivre.com.br/notebook-samsung-galaxy-book4-intel-core-i5-1335u-13-ghz-ate-46ghz-12-mb-l3-cache-windows-11-home-8gb-512gb-ssd-iris-xe-156-full-hd-led-155kg/p/MLB37044038",
        "Fonte técnica principal": "https://www.samsung.com/br/computers/samsung-book/galaxy-book4-15-6-inch-i5-8gb-512gb-np750xgj-kg3br/",
        "Fonte complementar": "https://news.samsung.com/br/samsung-lanca-novo-galaxy-book4-no-brasil",
        "GPU": "Intel Iris Xe Graphics",
        "CPU PassMark (multi)": 13769,
        "CPU PassMark (single)": 3242,
        "Preço atual (R$)": "N/D",
        "Resumo": "Leve, bateria de 54 Wh, RJ‑45, dois USB‑C e segundo slot M.2. A limitação mais importante é a RAM de 8 GB soldada.",
    },
    {
        "Marca": "Acer",
        "Modelo / configuração": "Aspire 16 A16-71M-55H0 — Ultra 5 115U / 16GB / 512GB",
        "Código / SKU": "NX.JQLAL.001",
        "Ano/geração aproximada": "2025 / Core Ultra Série 1",
        "Sistema operacional": "Windows 11 Home 64-bit",
        "CPU": "Intel Core Ultra 5 115U",
        "Família / geração CPU": "Core Ultra Série 1 (Meteor Lake-U)",
        "Arquitetura CPU": "Híbrida + LP E-core",
        "Núcleos": 8,
        "P-cores": 2,
        "E-cores": 4,
        "LP E-cores": 2,
        "Threads": 10,
        "Clock base / referência (GHz)": 1.5,
        "Turbo máx. (GHz)": 4.2,
        "Cache L3 (MB)": 10,
        "NPU": "Intel AI Boost",
        "GPU integrada": "Intel Graphics (3 Xe-cores, Meteor Lake)",
        "GPU dedicada": "Não",
        "RAM instalada (GB)": 16,
        "Tipo RAM": "LPDDR5",
        "Velocidade RAM": "até 6400 MT/s",
        "Configuração RAM": "16GB onboard dual-channel",
        "RAM soldada": "Sim",
        "Slots RAM físicos": 0,
        "Slots RAM livres": 0,
        "RAM máxima oficial (GB)": 16,
        "Dual-channel de fábrica": "Sim",
        "Expansão de RAM": "Não",
        "SSD instalado (GB)": 512,
        "Tipo/interface SSD": "NVMe PCIe 4.0 x4",
        "Formato SSD": "M.2 2280",
        "Slots M.2 totais": 1,
        "Slots M.2 livres": 0,
        "Armazenamento máx./observação": "Slot M.2 único; fabricante informa compatibilidade até 1TB",
        "Tela (pol.)": 16,
        "Resolução": "1920×1200",
        "Proporção": "16:10",
        "Painel": "IPS",
        "Acabamento": "Antirreflexo Acer ComfyView",
        "Touch": "Não",
        "Taxa de atualização (Hz)": 60,
        "Brilho (nits)": 300,
        "Cobertura de cores": "45% NTSC",
        "Contraste": "1000:1",
        "Webcam": "Full HD 1080p, até 60 fps",
        "Tampa de privacidade": "N/D",
        "Teclado ABNT2": "Sim",
        "Teclado numérico": "Sim",
        "Teclado retroiluminado": "Não",
        "Touchpad": "Precision Touchpad, resistente à umidade",
        "Wi‑Fi": "Wi‑Fi 6E 2×2",
        "Bluetooth": "5.1 ou superior",
        "Ethernet RJ‑45": "Não",
        "USB‑A": "2× USB 3.2 Gen 1 (5Gbps)",
        "USB‑C": "2× USB‑C",
        "Thunderbolt / USB4": "2× Thunderbolt 4",
        "USB‑C com vídeo": "Sim",
        "USB‑C com carregamento": "Sim",
        "HDMI": "1× HDMI 2.1",
        "Leitor de cartões": "Não",
        "Áudio P2": "1× combo 3,5 mm",
        "Áudio / alto-falantes": "2×2W, Acer TrueHarmony",
        "Microfones": "2×, Purified Voice 2.0",
        "Bateria (Wh)": 53,
        "Células": 3,
        "Autonomia declarada": "Até 8 h",
        "Carregador (W)": 65,
        "Carregamento USB‑C": "Sim",
        "Largura (mm)": 360.4,
        "Profundidade (mm)": 253.22,
        "Espessura (mm)": 17.95,
        "Peso (kg)": 1.69,
        "Material / construção": "Alumínio + plástico (anúncio)",
        "Cor": "Cinza aço",
        "TPM": "fTPM",
        "Trava de segurança": "Kensington",
        "Leitor biométrico": "Não",
        "Garantia informada": "12 meses",
        "Destaques objetivos": "16GB rápidos; 16:10 IPS 300 nits; 2× Thunderbolt 4; webcam FHD; NPU",
        "Limitações / ressalvas": "RAM soldada; sem RJ‑45; sem leitor de cartões; apenas um slot M.2",
        "Link do anúncio": "https://www.mercadolivre.com.br/notebook-16-acer-aspire-16-com-tela-wuxga-ips-1610-processador-intel-core-ultra-5-115u-16gb-ram-lpddr5-a-6400mhz-ssd-de-512gb-windows-11-home/p/MLB60328223",
        "Fonte técnica principal": "https://br-store.acer.com/notebook-acer-a16-71m-55h0--cu5115u--16gb--512gb-ssd--wnhpsl64--gray--lcd-16-nx-jqlal-001/p",
        "Fonte complementar": "https://store.acerempresas.com.br/notebook-acer-a16-71m-55h0--cu5115u--16gb--512gb-ssd--wnhpsl64--gray--lcd-16-nx-jqlal-001/p",
        "GPU": "Intel Graphics (3 Xe-cores, Meteor Lake)",
        "CPU PassMark (multi)": 12771,
        "CPU PassMark (single)": 3421,
        "Preço atual (R$)": "N/D",
        "Resumo": "Conjunto moderno com 16 GB LPDDR5, tela 16:10 de 300 nits, Thunderbolt 4, webcam FHD e NPU. RAM não é expansível.",
    },
    {
        "Marca": "Lenovo",
        "Modelo / configuração": "ThinkPad E14 (Gen 1) — i7-10510U / 8GB / 512GB",
        "Código / SKU": "20RA/20RB (submodelo não informado)",
        "Ano/geração aproximada": "2019–2020 / Intel 10ª",
        "Sistema operacional": "Não confirmado no anúncio",
        "CPU": "Intel Core i7-10510U",
        "Família / geração CPU": "10ª geração (Comet Lake-U)",
        "Arquitetura CPU": "Convencional",
        "Núcleos": 4,
        "P-cores": 4,
        "E-cores": 0,
        "LP E-cores": 0,
        "Threads": 8,
        "Clock base / referência (GHz)": 1.8,
        "Turbo máx. (GHz)": 4.9,
        "Cache L3 (MB)": 8,
        "NPU": "Não",
        "GPU integrada": "Intel UHD Graphics",
        "GPU dedicada": "Não determinável (família também teve Radeon 625/RX 640)",
        "RAM instalada (GB)": 8,
        "Tipo RAM": "DDR4",
        "Velocidade RAM": "2666 MT/s",
        "Configuração RAM": "1×8GB SO-DIMM (assumido pelo anúncio)",
        "RAM soldada": "Não",
        "Slots RAM físicos": 1,
        "Slots RAM livres": 0,
        "RAM máxima oficial (GB)": 16,
        "Dual-channel de fábrica": "Não (1 slot físico)",
        "Expansão de RAM": "Sim, substituindo módulo; até 16GB oficial",
        "SSD instalado (GB)": 512,
        "Tipo/interface SSD": "NVMe PCIe 3.0 (família)",
        "Formato SSD": "M.2 2242/2280 conforme submodelo",
        "Slots M.2 totais": 1,
        "Slots M.2 livres": 0,
        "Armazenamento máx./observação": "Até 2 unidades: 1× M.2 + 1× 2,5” SATA, conforme configuração física",
        "Tela (pol.)": 14,
        "Resolução": "1920×1080",
        "Proporção": "16:9",
        "Painel": "TN 220 nits OU IPS 250 nits",
        "Acabamento": "Antirreflexo",
        "Touch": "Não",
        "Taxa de atualização (Hz)": 60,
        "Brilho (nits)": "220 ou 250",
        "Cobertura de cores": "N/D",
        "Contraste": "400:1 (TN) / 700:1 (IPS)",
        "Webcam": "720p",
        "Tampa de privacidade": "Varia por submodelo",
        "Teclado ABNT2": "Provável; confirmar unidade",
        "Teclado numérico": "Não",
        "Teclado retroiluminado": "Opcional / não determinável",
        "Touchpad": "ThinkPad TrackPad + TrackPoint",
        "Wi‑Fi": "Wi‑Fi 5 ou Wi‑Fi 6 conforme placa",
        "Bluetooth": "Conforme placa WLAN",
        "Ethernet RJ‑45": "Sim, Gigabit",
        "USB‑A": "2× USB 3.1 Gen1 + 1× USB 2.0",
        "USB‑C": "1× USB‑C 3.1 Gen1",
        "Thunderbolt / USB4": "Não",
        "USB‑C com vídeo": "Sim (DisplayPort)",
        "USB‑C com carregamento": "Sim",
        "HDMI": "1× HDMI 1.4b",
        "Leitor de cartões": "Não",
        "Áudio P2": "1× combo 3,5 mm",
        "Áudio / alto-falantes": "2×2W, Dolby Advanced Audio",
        "Microfones": "2× array",
        "Bateria (Wh)": 45,
        "Células": "Integrada",
        "Autonomia declarada": "Até 12,8 h (MobileMark 2014; família)",
        "Carregador (W)": 65,
        "Carregamento USB‑C": "Sim",
        "Largura (mm)": 325,
        "Profundidade (mm)": 232,
        "Espessura (mm)": 18.9,
        "Peso (kg)": 1.69,
        "Material / construção": "Varia por submodelo: tampa em alumínio ou PC+ABS; base em alumínio ou PC+ABS",
        "Cor": "Preto",
        "TPM": "Sim",
        "Trava de segurança": "Kensington",
        "Leitor biométrico": "Opcional / não determinável",
        "Garantia informada": "Depende do vendedor/estado do equipamento",
        "Destaques objetivos": "Teclado/TrackPoint corporativo; RJ‑45; USB‑C com vídeo/carga; possibilidade de 2º drive SATA",
        "Limitações / ressalvas": "Modelo antigo; submodelo não informado impede determinar painel, WLAN, dGPU e biometria; bateria pode ter desgaste se usado/recondicionado",
        "Link do anúncio": "https://www.mercadolivre.com.br/notebook-lenovo-thinkpad-e14-core-i7-10-8gb-ram-512gb-ssd/up/MLBU3626973561",
        "Fonte técnica principal": "https://psref.lenovo.com/syspool/Sys/PDF/ThinkPad/ThinkPad_E14/ThinkPad_E14_Spec.pdf",
        "Fonte complementar": "https://psref.lenovo.com/syspool/Sys/i_pdf/psref562.pdf",
        "GPU": "Intel UHD Graphics",
        "CPU PassMark (multi)": 6335,
        "CPU PassMark (single)": 2191,
        "Preço atual (R$)": "N/D",
        "Resumo": "Construção e ergonomia corporativa, RJ‑45 e USB‑C com vídeo/carga. É uma plataforma muito mais antiga; submodelo incompleto gera incerteza.",
    },
    {
        "Marca": "ASUS",
        "Modelo / configuração": "Vivobook 16 X1605VA-MB763W — i7-1355U / 16GB / 512GB",
        "Código / SKU": "X1605VA-MB763W",
        "Ano/geração aproximada": "2023 / Intel 13ª",
        "Sistema operacional": "Windows 11 Home",
        "CPU": "Intel Core i7-1355U",
        "Família / geração CPU": "13ª geração (Raptor Lake-U)",
        "Arquitetura CPU": "Híbrida",
        "Núcleos": 10,
        "P-cores": 2,
        "E-cores": 8,
        "LP E-cores": 0,
        "Threads": 12,
        "Clock base / referência (GHz)": 1.7,
        "Turbo máx. (GHz)": 5.0,
        "Cache L3 (MB)": 12,
        "NPU": "Não",
        "GPU integrada": "Intel Iris Xe Graphics",
        "GPU dedicada": "Não",
        "RAM instalada (GB)": 16,
        "Tipo RAM": "DDR4",
        "Velocidade RAM": "3200 MT/s",
        "Configuração RAM": "8GB onboard + 8GB SO-DIMM",
        "RAM soldada": "Parcial (8GB)",
        "Slots RAM físicos": 1,
        "Slots RAM livres": 0,
        "RAM máxima oficial (GB)": 16,
        "Dual-channel de fábrica": "Sim",
        "Expansão de RAM": "Limitada; 8GB soldados + 1 SO-DIMM, máximo oficial 16GB",
        "SSD instalado (GB)": 512,
        "Tipo/interface SSD": "NVMe M.2",
        "Formato SSD": "M.2",
        "Slots M.2 totais": 1,
        "Slots M.2 livres": 0,
        "Armazenamento máx./observação": "1 slot M.2; capacidade depende de SSD substituto",
        "Tela (pol.)": 16,
        "Resolução": "1920×1200",
        "Proporção": "16:10",
        "Painel": "IPS-level",
        "Acabamento": "Antirreflexo",
        "Touch": "Não",
        "Taxa de atualização (Hz)": 60,
        "Brilho (nits)": 300,
        "Cobertura de cores": "45% NTSC",
        "Contraste": "N/D",
        "Webcam": "HD 720p",
        "Tampa de privacidade": "Sim",
        "Teclado ABNT2": "Sim (SKU BR)",
        "Teclado numérico": "Sim",
        "Teclado retroiluminado": "Não",
        "Touchpad": "Precision touchpad",
        "Wi‑Fi": "Wi‑Fi 5 (802.11ac) 1×1",
        "Bluetooth": "5.1",
        "Ethernet RJ‑45": "Não",
        "USB‑A": "2× USB 3.2 Gen1 + 1× USB 2.0",
        "USB‑C": "1× USB 3.2 Gen1 Type‑C",
        "Thunderbolt / USB4": "Não",
        "USB‑C com vídeo": "Não confirmado",
        "USB‑C com carregamento": "Sim (Power Delivery)",
        "HDMI": "1× HDMI 1.4",
        "Leitor de cartões": "Não",
        "Áudio P2": "1× combo 3,5 mm",
        "Áudio / alto-falantes": "SonicMaster estéreo",
        "Microfones": "Integrados; AI Noise Canceling",
        "Bateria (Wh)": 42,
        "Células": 3,
        "Autonomia declarada": "N/D",
        "Carregador (W)": 45,
        "Carregamento USB‑C": "SKU suporta PD, mas inclui carregador DC-in",
        "Largura (mm)": 358.7,
        "Profundidade (mm)": 249.5,
        "Espessura (mm)": 19.9,
        "Peso (kg)": 1.88,
        "Material / construção": "Plástico (família)",
        "Cor": "Cool Silver",
        "TPM": "Firmware TPM",
        "Trava de segurança": "N/D",
        "Leitor biométrico": "Não informado",
        "Garantia informada": "12 meses",
        "Destaques objetivos": "i7-1355U; 16GB em dual-channel; tela 16:10 300 nits; tampa física da webcam",
        "Limitações / ressalvas": "Wi‑Fi 5 1×1; HDMI 1.4; bateria de 42Wh; expansão de RAM limitada a 16GB oficial",
        "Link do anúncio": "https://www.mercadolivre.com.br/notebook-vivobook-16-intel-core-i7-1355u-16gb-ram-512gb-ssd-tela-16-full-hd-windows-11-asus/p/MLB39460220",
        "Fonte técnica principal": "https://b2b.lojaasus.com.br/notebook-asus-vivobook-16-x1605va-mb763w-cool-silver.html",
        "Fonte complementar": "https://www.asus.com/br/laptops/for-home/vivobook/vivobook-16-x1605/techspec/",
        "GPU": "Intel Iris Xe Graphics",
        "CPU PassMark (multi)": 13840,
        "CPU PassMark (single)": 3368,
        "Preço atual (R$)": "N/D",
        "Resumo": "i7-1355U, 16 GB em dual-channel e tela 16:10 de 300 nits. Bateria pequena e conectividade menos moderna.",
    },
    {
        "Marca": "HP",
        "Modelo / configuração": "200 G2i 16” — Core 5 120U / 8GB / 512GB",
        "Código / SKU": "E30QFAT#AK4",
        "Ano/geração aproximada": "2025–2026 / Core Série 1",
        "Sistema operacional": "Windows 11 Home Single Language",
        "CPU": "Intel Core 5 120U",
        "Família / geração CPU": "Intel Core Série 1 (Raptor Lake-U refresh)",
        "Arquitetura CPU": "Híbrida",
        "Núcleos": 10,
        "P-cores": 2,
        "E-cores": 8,
        "LP E-cores": 0,
        "Threads": 12,
        "Clock base / referência (GHz)": 1.4,
        "Turbo máx. (GHz)": 5.0,
        "Cache L3 (MB)": 12,
        "NPU": "Não",
        "GPU integrada": "Intel Graphics (80 EU; opera como UHD com RAM single-channel)",
        "GPU dedicada": "Não",
        "RAM instalada (GB)": 8,
        "Tipo RAM": "DDR5",
        "Velocidade RAM": "5200 MT/s",
        "Configuração RAM": "1×8GB SO-DIMM",
        "RAM soldada": "Não",
        "Slots RAM físicos": 2,
        "Slots RAM livres": 1,
        "RAM máxima oficial (GB)": 32,
        "Dual-channel de fábrica": "Não",
        "Expansão de RAM": "Sim; até 32GB oficial",
        "SSD instalado (GB)": 512,
        "Tipo/interface SSD": "PCIe Gen4 NVMe",
        "Formato SSD": "M.2",
        "Slots M.2 totais": 1,
        "Slots M.2 livres": 0,
        "Armazenamento máx./observação": "Família oferece SSDs até 1TB; substituir SSD para ampliar",
        "Tela (pol.)": 16,
        "Resolução": "1920×1200",
        "Proporção": "16:10",
        "Painel": "IPS / UWVA",
        "Acabamento": "Antirreflexo",
        "Touch": "Não",
        "Taxa de atualização (Hz)": 60,
        "Brilho (nits)": 300,
        "Cobertura de cores": "62,5% sRGB",
        "Contraste": "N/D",
        "Webcam": "FHD 1080p HDR (família/configuração correspondente)",
        "Tampa de privacidade": "N/D",
        "Teclado ABNT2": "Sim (SKU BR)",
        "Teclado numérico": "Sim",
        "Teclado retroiluminado": "Não informado",
        "Touchpad": "Clickpad multitoque",
        "Wi‑Fi": "Wi‑Fi 6 (Realtek 8852BE-VT, configuração comum)",
        "Bluetooth": "5.4 (com Wi‑Fi 6)",
        "Ethernet RJ‑45": "Sim, Gigabit",
        "USB‑A": "2× USB 3.2 Gen1",
        "USB‑C": "2× USB 3.2 Gen2 Type‑C 10Gbps",
        "Thunderbolt / USB4": "Não",
        "USB‑C com vídeo": "Sim, DisplayPort 1.4",
        "USB‑C com carregamento": "Sim, USB Power Delivery",
        "HDMI": "1× HDMI 1.4b",
        "Leitor de cartões": "Não informado",
        "Áudio P2": "1× combo 3,5 mm",
        "Áudio / alto-falantes": "Poly Studio, 2 estéreo",
        "Microfones": "2× array, redução de ruído por IA",
        "Bateria (Wh)": 41,
        "Células": 3,
        "Autonomia declarada": "N/D",
        "Carregador (W)": 65,
        "Carregamento USB‑C": "Sim",
        "Largura (mm)": 358.6,
        "Profundidade (mm)": 251.8,
        "Espessura (mm)": 18.9,
        "Peso (kg)": 1.72,
        "Material / construção": "Plástico / linha corporativa básica",
        "Cor": "Prata",
        "TPM": "Sim",
        "Trava de segurança": "Sim",
        "Leitor biométrico": "Não informado",
        "Garantia informada": "12 meses (confirmar anúncio)",
        "Destaques objetivos": "RAM expansível até 32GB; 2× USB‑C 10Gbps com DP/PD; RJ‑45; tela 16:10 300 nits; webcam FHD",
        "Limitações / ressalvas": "8GB em single-channel de fábrica; bateria 41Wh; algumas características variam por WLAN/lote",
        "Link do anúncio": "https://www.mercadolivre.com.br/notebook-hp-200-g2i-intel-core-5-120u-16-intel-graphics-ram-8gb-1x8gb-ddr5-5200-ssd-512gb-pcie4x4-windows-11-home-sl-e30qfatak4/p/MLB78311028",
        "Fonte técnica principal": "https://support.hp.com/br-pt/document/ish_13834797-13835475-16",
        "Fonte complementar": "https://www.hp.com/za-en/products/laptops/product-details/product-specifications/2104283715",
        "GPU": "Intel Graphics (80 EU; opera como UHD com RAM single-channel)",
        "CPU PassMark (multi)": 14862,
        "CPU PassMark (single)": 3456,
        "Preço atual (R$)": "N/D",
        "Resumo": "RAM DDR5 expansível até 32 GB, dois USB‑C 10 Gbps com vídeo/carga, RJ‑45 e webcam FHD. Sai de fábrica com 8 GB single-channel.",
    },
    {
        "Marca": "Dell",
        "Modelo / configuração": "Dell 15 DC15-I51334U-A50 — i5-1334U / 8GB / 512GB",
        "Código / SKU": "DC15-I51334U-A50 / 210-BWBG",
        "Ano/geração aproximada": "2026 / Intel 13ª",
        "Sistema operacional": "Windows 11 Home",
        "CPU": "Intel Core i5-1334U",
        "Família / geração CPU": "13ª geração (Raptor Lake-U)",
        "Arquitetura CPU": "Híbrida",
        "Núcleos": 10,
        "P-cores": 2,
        "E-cores": 8,
        "LP E-cores": 0,
        "Threads": 12,
        "Clock base / referência (GHz)": 1.3,
        "Turbo máx. (GHz)": 4.6,
        "Cache L3 (MB)": 12,
        "NPU": "Não",
        "GPU integrada": "Intel UHD Graphics (Iris Xe 80 EU limitada por RAM single-channel)",
        "GPU dedicada": "Não",
        "RAM instalada (GB)": 8,
        "Tipo RAM": "DDR5",
        "Velocidade RAM": "4400 MT/s",
        "Configuração RAM": "1×8GB SO-DIMM",
        "RAM soldada": "Não",
        "Slots RAM físicos": 2,
        "Slots RAM livres": 1,
        "RAM máxima oficial (GB)": 16,
        "Dual-channel de fábrica": "Não",
        "Expansão de RAM": "Sim; até 16GB informado",
        "SSD instalado (GB)": 512,
        "Tipo/interface SSD": "PCIe NVMe",
        "Formato SSD": "M.2",
        "Slots M.2 totais": 1,
        "Slots M.2 livres": 0,
        "Armazenamento máx./observação": "Substituição do M.2 para ampliar",
        "Tela (pol.)": 15.6,
        "Resolução": "1920×1080",
        "Proporção": "16:9",
        "Painel": "WVA",
        "Acabamento": "Antirreflexo",
        "Touch": "Não",
        "Taxa de atualização (Hz)": 120,
        "Brilho (nits)": 250,
        "Cobertura de cores": "N/D",
        "Contraste": "600:1",
        "Webcam": "HD 720p widescreen",
        "Tampa de privacidade": "N/D",
        "Teclado ABNT2": "Sim",
        "Teclado numérico": "Sim",
        "Teclado retroiluminado": "Não",
        "Touchpad": "Precision touchpad",
        "Wi‑Fi": "Wi‑Fi 6 Realtek RTL8852BE 2×2",
        "Bluetooth": "Sim (placa combinada)",
        "Ethernet RJ‑45": "Não",
        "USB‑A": "1× USB 3.2 Gen1 + 1× USB 2.0",
        "USB‑C": "1× USB 3.2 Gen1 Type‑C (dados)",
        "Thunderbolt / USB4": "Não",
        "USB‑C com vídeo": "Não",
        "USB‑C com carregamento": "Não",
        "HDMI": "1× HDMI 1.4",
        "Leitor de cartões": "SD",
        "Áudio P2": "1× combo 3,5 mm",
        "Áudio / alto-falantes": "Waves MaxxAudio Pro",
        "Microfones": "1× digital",
        "Bateria (Wh)": 41,
        "Células": 3,
        "Autonomia declarada": "Não especificada",
        "Carregador (W)": 65,
        "Carregamento USB‑C": "Não",
        "Largura (mm)": 358.5,
        "Profundidade (mm)": 235.5,
        "Espessura (mm)": 18.9,
        "Peso (kg)": 1.63,
        "Material / construção": "Plástico",
        "Cor": "Preto Carbono",
        "TPM": "Sim",
        "Trava de segurança": "N/D",
        "Leitor biométrico": "Não",
        "Garantia informada": "12 meses",
        "Destaques objetivos": "Tela 120Hz; RAM expansível; leitor SD; peso relativamente baixo",
        "Limitações / ressalvas": "8GB single-channel; USB‑C apenas dados; sem RJ‑45; bateria 41Wh; limite oficial de RAM 16GB",
        "Link do anúncio": "https://www.mercadolivre.com.br/notebook-dell-dc15-i51334u-a50-156-fhd-i5-8gb-512gb-win-11/p/MLB70040749",
        "Fonte técnica principal": "https://www.magazineluiza.com.br/notebook-dell-15-dc15-i51334u-a50-intel-core-i5-8gb-ram-512gb-ssd-156-full-hd-windows-11-210-bwbg/p/241623300/in/nodl/",
        "Fonte complementar": "https://quenotebookcomprar.com.br/dell-15-dc15-i51334u-a50/",
        "GPU": "Intel UHD Graphics (Iris Xe 80 EU limitada por RAM single-channel)",
        "CPU PassMark (multi)": 12991,
        "CPU PassMark (single)": 3229,
        "Preço atual (R$)": "N/D",
        "Resumo": "Tela 120 Hz e RAM expansível, mas apenas 8 GB de fábrica, USB‑C somente dados e bateria de 41 Wh.",
    },
    {
        "Marca": "Dell",
        "Modelo / configuração": "Dell 15 DC15-I51334U-M80 — i5-1334U / 16GB / 1TB",
        "Código / SKU": "DC15-I51334U-M80",
        "Ano/geração aproximada": "2026 / Intel 13ª",
        "Sistema operacional": "Windows 11 Home",
        "CPU": "Intel Core i5-1334U",
        "Família / geração CPU": "13ª geração (Raptor Lake-U)",
        "Arquitetura CPU": "Híbrida",
        "Núcleos": 10,
        "P-cores": 2,
        "E-cores": 8,
        "LP E-cores": 0,
        "Threads": 12,
        "Clock base / referência (GHz)": 1.3,
        "Turbo máx. (GHz)": 4.6,
        "Cache L3 (MB)": 12,
        "NPU": "Não",
        "GPU integrada": "Intel UHD Graphics (Iris Xe 80 EU limitada por RAM single-channel)",
        "GPU dedicada": "Não",
        "RAM instalada (GB)": 16,
        "Tipo RAM": "DDR5",
        "Velocidade RAM": "4400 MT/s",
        "Configuração RAM": "1×16GB SO-DIMM",
        "RAM soldada": "Não",
        "Slots RAM físicos": 2,
        "Slots RAM livres": 1,
        "RAM máxima oficial (GB)": 16,
        "Dual-channel de fábrica": "Não (1×16GB)",
        "Expansão de RAM": "Limite de 16GB informado; slot físico livre sem ganho oficial de capacidade",
        "SSD instalado (GB)": 1024,
        "Tipo/interface SSD": "PCIe NVMe",
        "Formato SSD": "M.2",
        "Slots M.2 totais": 1,
        "Slots M.2 livres": 0,
        "Armazenamento máx./observação": "1TB de fábrica; ampliar requer substituição",
        "Tela (pol.)": 15.6,
        "Resolução": "1920×1080",
        "Proporção": "16:9",
        "Painel": "WVA",
        "Acabamento": "Antirreflexo",
        "Touch": "Não",
        "Taxa de atualização (Hz)": 120,
        "Brilho (nits)": 250,
        "Cobertura de cores": "N/D",
        "Contraste": "600:1",
        "Webcam": "HD 720p widescreen",
        "Tampa de privacidade": "N/D",
        "Teclado ABNT2": "Sim",
        "Teclado numérico": "Sim",
        "Teclado retroiluminado": "Não",
        "Touchpad": "Precision touchpad",
        "Wi‑Fi": "Wi‑Fi 6 Realtek RTL8852BE 2×2",
        "Bluetooth": "Sim (placa combinada)",
        "Ethernet RJ‑45": "Não",
        "USB‑A": "1× USB 3.2 Gen1 + 1× USB 2.0",
        "USB‑C": "1× USB 3.2 Gen1 Type‑C (dados)",
        "Thunderbolt / USB4": "Não",
        "USB‑C com vídeo": "Não",
        "USB‑C com carregamento": "Não",
        "HDMI": "1× HDMI 1.4",
        "Leitor de cartões": "SD",
        "Áudio P2": "1× combo 3,5 mm",
        "Áudio / alto-falantes": "Waves MaxxAudio Pro",
        "Microfones": "1× digital",
        "Bateria (Wh)": 41,
        "Células": 3,
        "Autonomia declarada": "Não especificada",
        "Carregador (W)": 65,
        "Carregamento USB‑C": "Não",
        "Largura (mm)": 358.5,
        "Profundidade (mm)": 235.5,
        "Espessura (mm)": 18.9,
        "Peso (kg)": 1.63,
        "Material / construção": "Plástico",
        "Cor": "Preto Carbono",
        "TPM": "Sim",
        "Trava de segurança": "N/D",
        "Leitor biométrico": "Não",
        "Garantia informada": "12 meses",
        "Destaques objetivos": "16GB e 1TB de fábrica; tela 120Hz; leitor SD; peso relativamente baixo",
        "Limitações / ressalvas": "16GB em módulo único; USB‑C apenas dados; sem RJ‑45; bateria 41Wh; limite de RAM oficial já atingido",
        "Link do anúncio": "https://www.mercadolivre.com.br/dell-inspiron-dc15-i51334u-m80-notebook-156-i5-16gb-1tb-ssd-tela-antirreflexo/p/MLB76590114",
        "Fonte técnica principal": "https://www.magazineluiza.com.br/notebook-dell-15-dc15-i51334u-m80-15-6-full-hd-13a-gen-intel-core-i5-16gb-1tb-ssd-win-11-preto-carbono/p/jc0448k2f9/in/nodl/",
        "Fonte complementar": "https://www.kabum.com.br/produto/1028017/notebook-dell-inspiron-dc15-i51334u-m80-15-6-full-hd-13-gen-intel-core-i5-16gb-1tb-ssd-win-11-preto-carbono",
        "GPU": "Intel UHD Graphics (Iris Xe 80 EU limitada por RAM single-channel)",
        "CPU PassMark (multi)": 12991,
        "CPU PassMark (single)": 3229,
        "Preço atual (R$)": "N/D",
        "Resumo": "Mesmo chassi do A50, com 16 GB e SSD de 1 TB. Tela 120 Hz; USB‑C continua limitado a dados e a bateria é de 41 Wh.",
    },
]
